artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  curr_data_path: US_Accidents_March23 copy.csv 
  store_data_path: artifacts/data_ingestion/data.csv  

data_cleaning:
  root_dir: artifacts/data_cleaning
  main_data_dir: artifacts/main_data
  curr_file_path: artifacts/data_ingestion/data.csv
  clean_file_path: artifacts/data_cleaning/clean_data.csv
  train_file_path: artifacts/main_data/train_data.csv
  test_file_path: artifacts/main_data/test_data.csv

preprocessing:
  root_dir: artifacts/preprocessing
  preprocesser_obj: artifacts/preprocessing/preprocesser.pkl
  train_file_path: artifacts/main_data/train_data.csv
  test_file_path: artifacts/main_data/test_data.csv
  preprocessed_x_train: artifacts/preprocessing/x_train_trf.npy
  preprocessed_x_test: artifacts/preprocessing/x_test_trf.npy
  preprocessed_y_train: artifacts/preprocessing/y_train_trf.npy
  preprocessed_y_test: artifacts/preprocessing/y_test_trf.npy

model_trainer:
  root_dir: artifacts/model_trainer
  results: artifacts/model_trainer/results.txt
  preprocessed_x_train: artifacts/preprocessing/x_train_trf.npy
  preprocessed_x_test: artifacts/preprocessing/x_test_trf.npy
  preprocessed_y_train: artifacts/preprocessing/y_train_trf.npy
  preprocessed_y_test: artifacts/preprocessing/y_test_trf.npy